export const TODO_ADD_ITEM_REQUEST = "TODO_ADD_ITEM_REQUEST";
export const TODO_ADD_ITEM_SUCCESS = "TODO_ADD_ITEM_SUCCESS";

export const TODO_EDIT_ITEM_REQUEST = "TODO_EDIT_ITEM_REQUEST";
export const TODO_EDIT_ITEM_SUCCESS = "TODO_EDIT_ITEM_SUCCESS";

export const TODO_DELETE_ITEM_REQUEST = "TODO_DELETE_ITEM_REQUEST";
export const TODO_DELETE_ITEM_SUCCESS = "TODO_DELETE_ITEM_SUCCESS";

export const TODO_SEARCH_ITEM_REQUEST = "TODO_SEARCH_ITEM_REQUEST";
export const TODO_SEARCH_ITEM_SUCCESS = "TODO_SEARCH_ITEM_SUCCESS";

export const TODO_FETCH_ITEMS_REQUEST = "TODO_FETCH_ITEMS_REQUEST";
export const TODO_FETCH_ITEMS_SUCCESS = "TODO_FETCH_ITEMS_SUCCESS";
